# Generated by Django 2.0.6 on 2018-08-17 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('views', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('stars', models.IntegerField(default=0, verbose_name='赞赏次数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '博客列表',
            },
        ),
        migrations.CreateModel(
            name='Blogtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='类别')),
                ('discription', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blogtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blogtype', verbose_name='分类'),
        ),
    ]
