# Generated by Django 2.0.6 on 2018-08-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktype', models.CharField(max_length=120, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '书本分类',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.IntegerField(default='**', verbose_name='章节数')),
                ('chapter_title', models.CharField(max_length=120, verbose_name='章节')),
                ('text', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '章节内容',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=120, verbose_name='书名')),
                ('summary', models.CharField(default='暂无', max_length=120, verbose_name='简介')),
                ('author', models.CharField(default='暂无', max_length=120, verbose_name='作者')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('search_count', models.IntegerField(default=0, verbose_name='搜索量')),
                ('booktype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novels.Booktype', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '书本信息',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='bookname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Novel', verbose_name='书名'),
        ),
    ]
